apiVersion: v1
kind: ClusterRole
metadata:
  annotations:
    authorization.openshift.io/system-only: "true"
  name: openshiftbuilddeploy
  resourceVersion: "10"
rules:
- apiGroups:
  - project.openshift.io
  - ""
  attributeRestrictions: null
  resources:
  - projects
  verbs:
  - get
- apiGroups:
  - project.openshift.io
  - ""
  attributeRestrictions: null
  resources:
  - projectrequests
  verbs:
  - create
- apiGroups:
  - build.openshift.io
  - ""
  attributeRestrictions: null
  resources:
  - builds/custom
  verbs:
  - create