apiVersion: v1
kind: Template
metadata:
  creationTimestamp: null
  name: lagoon-docker-host
parameters:
  - name: IMAGE
    description: Image that should be used
    value: docker.io/amazeeiolagoon/master-docker-host
  - name: REPOSITORY_TO_UPDATE
    description: Repository that should be updated by the cronjob
    value: amazeeio
objects:
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    labels:
      app: docker-host
    name: docker-host
  spec:
    replicas: 1
    selector:
      app: docker-host
      deploymentconfig: docker-host
    strategy:
      type: Recreate
    template:
      metadata:
        labels:
          app: docker-host
          deploymentconfig: docker-host
      spec:
        containers:
        - image: ${IMAGE}
          imagePullPolicy: Always
          livenessProbe:
            failureThreshold: 3
            periodSeconds: 10
            successThreshold: 1
            tcpSocket:
              port: 2375
            timeoutSeconds: 1
          name: docker-host
          env:
            - name: DOCKER_HOST
              value: localhost
            - name: REPOSITORY_TO_UPDATE
              value: ${REPOSITORY_TO_UPDATE}
          ports:
          - containerPort: 2375
            protocol: TCP
          readinessProbe:
            failureThreshold: 3
            periodSeconds: 10
            successThreshold: 1
            tcpSocket:
              port: 2375
            timeoutSeconds: 1
          resources: {}
          securityContext:
            privileged: true
          volumeMounts:
          - mountPath: /var/lib/docker
            name: docker-lib
        restartPolicy: Always
        serviceAccount: docker-host
        serviceAccountName: docker-host
        volumes:
        - name: docker-lib
          emptyDir: {}
    test: false
    triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
        - docker-host
        from:
          kind: ImageStreamTag
          name: docker-host:latest
      type: ImageChange
- apiVersion: v1
  kind: Service
  metadata:
    creationTimestamp: null
    labels:
      app: docker-host
    name: docker-host
  spec:
    ports:
    - port: 2375
      protocol: TCP
      targetPort: 2375
    selector:
      app: docker-host
      deploymentconfig: docker-host
  status:
    loadBalancer: {}