apiVersion: v1
kind: PolicyBinding
metadata:
  creationTimestamp: null
  name: lagoon:default
policyRef:
  name: default
  namespace: lagoon
roleBindings:
- name: shared-resource-viewer
  roleBinding:
    groupNames:
    - system:authenticated
    metadata:
      name: shared-resource-viewer
      namespace: lagoon
    roleRef:
      name: shared-resource-viewer
      namespace: lagoon
    subjects:
    - kind: SystemGroup
      name: system:authenticated
    userNames: null