apiVersion: mariadb.amazee.io/v1
kind: MariaDBProvider
metadata:
  name: mariadbprovider-development
spec:
  environment: development
  hostname: development.172.17.0.1.nip.io
  readreplica_hostnames:
  - development.replica.172.17.0.1.nip.io
  password: password
  port: '3306'
  user: root
---
apiVersion: mariadb.amazee.io/v1
kind: MariaDBProvider
metadata:
  name: mariadbprovider-production
spec:
  environment: production
  hostname: production.172.17.0.1.nip.io
  readreplica_hostnames:
  - production.replica.172.17.0.1.nip.io
  password: password
  port: '3306'
  user: root