apiVersion: v1
kind: Service
metadata:
  name: {{ include "lagoon-remote.dockerHost.fullname" . }}
  labels:
    {{- include "lagoon-remote.dockerHost.labels" . | nindent 4 }}
spec:
  type: {{ .Values.dockerHost.service.type }}
  ports:
    - port: {{ .Values.dockerHost.service.port }}
      targetPort: 2375
      protocol: TCP
      name: docker-daemon-tcp
  selector:
    {{- include "lagoon-remote.dockerHost.selectorLabels" . | nindent 4 }}
