apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "lagoon-remote.kubernetesbuilddeploy.serviceAccountName" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
{{ include "lagoon-remote.labels" . | nindent 4 }}